### ISSUE TITLE
Cannot import single quotation character

### ISSUE THREAD

**Issue by lqdung863** [huy8687/SpeakingChamber#11]
Nếu file input để import có chứa ký tự ' thì sau khi import, database tự động chuyển thành ký tự không đọc được
![04](https://user-images.githubusercontent.com/30969821/29300627-cebeb174-81a0-11e7-8d90-b5372837ca67.png)
![05](https://user-images.githubusercontent.com/30969821/29300636-d7c95c74-81a0-11e7-9a68-674b5c1468cb.png)

File data mẫu: 
[questions.txt](https://github.com/huy8687/SpeakingChamber/files/1224019/questions.txt)

**Comment by huybuidac** [comment]
@lqdung863 trong ảnh hình như a đang k dùng kí tự ' bình thường.
Nó nghiêng nghiêng kìa. a comment kí tự đó vào đây đc k a?

**Comment by lqdung863** [comment]
Uh, đúng là thế thật. Mắt tinh thế :D.
Đây là lỗi của input data. Anh cancel issue nhé.
