### ISSUE TITLE
Wrong date in Complete screen

### ISSUE THREAD

**Issue by lqdung863** [huy8687/SpeakingChamber#12]
Hiện tại, ở màn hình Complete screen, date đang để là ngày sinh của thí sinh.
Mong muốn: Date là ngày hiện tại.

**Comment by huybuidac** [comment]
fixed

**Comment by lqdung863** [comment]
Quên béng mất, màn hình "Start" khi bắt đầu test cũng bị lỗi y hệt T__T.
Fix nốt cả màn hình đó luôn giúp anh nhé.

**Comment by lqdung863** [comment]
Confirmed OK with v1.0b. Thanks
