### ISSUE TITLE
Cannot quit "Complete screen" while network is disconnect

### ISSUE THREAD

**Issue by lqdung863** [huy8687/SpeakingChamber#15]
Sau khi kết thúc bài thi, trong quá trình upload file lên Network Path, anh rút dây mạng. Kết quả là app bị treo mãi ở màn hình Complete mà ko thoát được.

![06](https://user-images.githubusercontent.com/30969821/29303147-befb07ce-81b4-11e7-9269-982e01f76d78.png)

Mong muốn: hiển thị được thông báo:
Cannot upload files to network path. Your files are saved in local path.
Và cho phép ấn OK để quay về màn hình khởi động như trường hợp bt.

**Comment by huybuidac** [comment]
fixed

**Comment by lqdung863** [comment]
Confirmed OK with v1.0. Thanks
