### ISSUE TITLE
[Improvement] Try to reduce the size of mp3 output file

### ISSUE THREAD

**Issue by lqdung863** [huy8687/SpeakingChamber#16]
Hiện tại các file output MP3 đang khá lớn.
1 file 1 phút = 10MB - tương đương dung lượng file .wav chuẩn.
Em thử xem có thể giảm dung lượng xuống được ko.
kiểu tương đương với file mp3 thông thường: 1 phút = 1MB ấy.
Thank.

**Comment by lqdung863** [comment]
Cái này là improvement thôi chứ :P. Dù specs ko nói rõ nhưng mà file mp3 lớn thế sao dùng được :D

**Comment by huybuidac** [comment]
ok a, để em thử reduce

**Comment by lqdung863** [comment]
Confirm OK, thanks
