### ISSUE TITLE
Replace image of "Complete" screen

### ISSUE THREAD

**Issue by lqdung863** [huy8687/SpeakingChamber#18]
Thay ảnh bảng thông báo của màn hình Complete như sau giúp anh nhé.

[Image.zip](https://github.com/huy8687/SpeakingChamber/files/1224755/Image.zip)

**Comment by huybuidac** [comment]
Updated

![new_complete](https://user-images.githubusercontent.com/7322305/29312045-00e1c294-81de-11e7-992c-65008e43d87e.PNG)

**Comment by lqdung863** [comment]
Confirmed OK with v1.0. Thanks
