### ISSUE TITLE
Release Speaking Chamber v1.0

### ISSUE THREAD

**Issue by huybuidac** [huy8687/SpeakingChamber#19]
Em gửi bản 1.0 nhé:

[SpeakingChamber_v1.0c.zip](https://github.com/huy8687/SpeakingChamber/files/1225819/SpeakingChamber_v1.0c.zip)

Resolve:
#18 
#17 
#15 
#14 
#13 
#12 
#10

**Comment by lqdung863** [comment]
Lỗi ngay phát đầu nhé T__T
Giao diện bị cái gì đè lên mất câu hỏi rồi

![08](https://user-images.githubusercontent.com/30969821/29325114-caae9e62-8210-11e7-8912-b1454d9ca7c6.png)

**Comment by huybuidac** [comment]
í, sr a, e làm con video 60% màn hình cuối, quên k check câu hỏi thường

**Comment by huybuidac** [comment]
@lqdung863 Em update link r nhé, fix cái trên với Date ở màn hình "Start"

**Comment by lqdung863** [comment]
Thank em. 2 cái đó OK rồi nhé.
Fix nốt cái #14 rồi anh close luôn cả ticket này, chốt version 1.0 nhé

**Comment by huybuidac** [comment]
Done a nhé

**Comment by lqdung863** [comment]
Confirm release OK. Demo was successful too. Thanks.
