### ISSUE TITLE
[Phase 2] Improve layout of "Select a test" screen

### ISSUE THREAD

**Issue by lqdung863** [huy8687/SpeakingChamber#21]
Ở màn hình "Select a test", hiện tại layout đang căn giữa, phần hiển thị cũng khá hẹp nên hình hơi xấu.

![09](https://user-images.githubusercontent.com/30969821/29488219-b81ef346-8530-11e7-9eaa-f98678403b9f.png)

Mong muốn:
- Align Left
- Danh sách các bài hiển thị dàn đều màn hình, với margin 2 bên tầm 8% độ rộng màn hình (flexible như vậy được thì tốt)

**Comment by lqdung863** [comment]
Sorry, giờ anh mới nhìn thấy lỗi chính tả. Hiện ở màn hình này đang viết sai chính tả. Em sửa lại giúp anh nhé:
Please do not select the tests which you completed before.

**Comment by lqdung863** [comment]
-- wrong comment ---

**Comment by huybuidac** [comment]
fixed

![issue_21](https://user-images.githubusercontent.com/7322305/29674806-711d104a-891d-11e7-8f93-7f214d9ee4d8.png)

**Comment by lqdung863** [comment]
Evidence bằng screenshot ở trên là đủ, close issue khỏi cần test :-"
