### ISSUE TITLE
[Phase 2] Update folder structure

### ISSUE THREAD

**Issue by lqdung863** [huy8687/SpeakingChamber#23]
Cấu trúc folder để lưu file output .mp3 ở version 1.x: 
Path\<ddmmyyy>\<Name>_<Date of birth>\....

Mong muốn: Đổi lại folder lưu file output như sau:
Path\<Name>_<Date of birth>\<yyyymmdd>\....

(Lưu ý: trong tên file mp3 cũng như tên folder, ngày phải để định dạng yyyymmdd. Ở version 1.x đang để là  ddmmyyyy)

**Comment by huybuidac** [comment]
> Cấu trúc folder để lưu file output .mp3 ở version 1.x:
> Path<ddmmyyy><Name>_....
> 
> Mong muốn: Đổi lại folder lưu file output như sau:
> Path<Name>_<yyyymmdd>....

@lqdung863 cái này là sao a nhỉ, e ko hiểu lắm. Ví dụ

> LocalPath = C:/SpeakChamber
> Uesr = Huy
> Dob = 2051993

=> thì save như nào vào local a

**Comment by lqdung863** [comment]
Hic, sorry. Chắc lúc đấy anh buồn ngủ quá, nên viết linh tinh. Ý anh là:
Cũ: C:\SpeakingChamber\23082017\Huy_20051993

Mới:
C:\SpeakingChamber\Huy_19930520\20170823

**Comment by lqdung863** [comment]
Confirm OK. Thanks
