### ISSUE TITLE
[Phase 2] Add video instruction

### ISSUE THREAD

**Issue by lqdung863** [huy8687/SpeakingChamber#24]
Tham khảo page 8, 9 ở tài liệu spec version 2.0 dưới đây:
[SpeakingChamber_ProductDescription_v2.0.pptx](https://github.com/huy8687/SpeakingChamber/files/1237193/SpeakingChamber_ProductDescription_v2.0.pptx)

**Comment by lqdung863** [comment]
Cái chữ "Instruction" em bôi đậm và to hơn hẳn các text còn lại giúp anh nhé

**Comment by lqdung863** [comment]
"recommended to see an instructional video" đang viết sai chính tả nhé.

**Comment by huybuidac** [comment]
fixed

![issue_24](https://user-images.githubusercontent.com/7322305/29675205-af108142-891e-11e7-945d-b00f9717a70b.jpg)

**Comment by lqdung863** [comment]
Evidence bằng screenshot ở trên là đủ, close issue ko cần test :-"
