### ISSUE TITLE
[Phase 2] Improve UX of Recording behavior

### ISSUE THREAD

**Issue by lqdung863** [huy8687/SpeakingChamber#25]
Mục tiêu: cần làm cho user dễ dàng nhận ra và hiểu là chương trình đang ghi âm giọng nói của họ.

Thay đổi như các slide 11, 12, 16, 24.
[SpeakingChamber_ProductDescription_v2.0.pptx](https://github.com/huy8687/SpeakingChamber/files/1237193/SpeakingChamber_ProductDescription_v2.0.pptx)

Nội dung thay đổi: 
- thêm icon để biểu thị việc "Recording"
- sửa nội dung các button next sang câu hỏi khác

**Comment by lqdung863** [comment]
Màn hình check Microphone ấy, em cho chữ "Please check your microphone" căn giữa nhé. Thanks

**Comment by huybuidac** [comment]
fixed, con này design ban đầu là trái mà a nhỉ

![issue_25](https://user-images.githubusercontent.com/7322305/29675374-2d051f68-891f-11e7-9c7b-6a485f820023.jpg)

**Comment by lqdung863** [comment]
Uh, nhưng vì cả cái khối bên dưới nó căn giữa đâm ra...
Anh close issue này nhé
