### ISSUE TITLE
[Phase 2] New feature: Allow student to review his/her answer.

### ISSUE THREAD

**Issue by lqdung863** [huy8687/SpeakingChamber#27]
Tham khảo nội dung thay đổi ở các slide 25, 26, 27 trong tài liệu dưới đây

[SpeakingChamber_ProductDescription_v2.0.pptx](https://github.com/huy8687/SpeakingChamber/files/1237193/SpeakingChamber_ProductDescription_v2.0.pptx)

**Comment by huybuidac** [comment]
@lqdung863 đoạn show video e thấy design là ko show nút Stop vs Next, e nghĩ là nên show ra.

**Comment by lqdung863** [comment]
Anh nghĩ ko cần đâu. Các video thường cũng ngắn thôi mà.
Nhưng sorry anh có một change request nho nhỏ, hết câu hỏi review cuối cùng, hoặc user ấn vào nút Stop Review, em cho ra màn hình "Congratulations" thay vì màn hình login nhé.

Với cả câu hỏi ở màn hình "Congratulations" đang sai chính tả từ hear nhé.

**Comment by lqdung863** [comment]
Confirm OK. Thanks!
