### ISSUE TITLE
[Phase2] Release SpeakingChamber

### ISSUE THREAD

**Issue by huybuidac** [huy8687/SpeakingChamber#28]
Em gửi app phase 2 nhé: đã contain hết các req

[SpeakingChamber_v1.4.zip](https://github.com/huy8687/SpeakingChamber/files/1249719/SpeakingChamber_v1.4.zip)

**Comment by huybuidac** [comment]
Em update lại app, fix một số issue

**Comment by huybuidac** [comment]
em update #27 #26  rồi nhé

**Comment by lqdung863** [comment]
Anh confirm OK và nhận release này nhé. Thank you very much!
