### ISSUE TITLE
Force close while checking microphone

### ISSUE THREAD

**Issue by lqdung863** [huy8687/SpeakingChamber#3]
Màn hình "check your microphone", hiển thị thông tin lạ (chắc là sound card driver).
Khi click vào "Complete" thì force close.

Máy: HP 8570w, Windows 7 Professionals.

![01](https://user-images.githubusercontent.com/30969821/29246372-2c31bb24-8022-11e7-94e9-e1392fb35335.png)

**Comment by huybuidac** [comment]
@lqdung863 máy a có 2 cards nên hiện ra, a chọn 1 trong 2 cái tiếp tục.

Force close thì e sẽ fix
